language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "apt-get install clamdscan" 
  - "python setup.py -q install"
  - "pip install pytest-pep8"
# command to run tests
script: pytest

